name: Schedules

#on:
#  schedule:
#    # This will run every day at 09:30 UTC+7
#    - cron: '*/5 * * * *'
#    # This will run every Monday at 09:30 UTC+7
#    - cron: '30 2 * * 1'
#    # This will run on the 1st of every month at 09:30 UTC+7
#    - cron: '30 2 1 * *'

on:
  push:
    branches: [ "feat/github_action" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth login --with-token

      - name: Get latest tag
        id: get_latest_release
        run: |
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          echo "Latest release tag: $latest_tag"
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Checkout latest release tag
        run: git checkout ${{ steps.get_latest_release.outputs.latest_tag }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build
        run: go build -v ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute
        env:
          ENV: "action"
#          PAT: ${{ secrets.GITHUB_PAT }}
        run: ./duck-bot